/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package examendifeb;

import java.awt.Cursor;

/**
 *
 * @author rocio
 */
public class Principal extends javax.swing.JFrame {
    //Variables para poder mover el panel (las utilizamos en el Panel del titulo, el panel superior)Lo hacemos con un event> moust>mousePressed
    int xMouse, yMouse;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PanelFondo = new javax.swing.JPanel();
        Titulo = new javax.swing.JPanel();
        PanelCerrar = new javax.swing.JPanel();
        LetraX = new javax.swing.JLabel();
        Letras = new javax.swing.JPanel();
        Reservar = new javax.swing.JButton();
        Nombre = new javax.swing.JLabel();
        Nom = new javax.swing.JTextField();
        Texto = new javax.swing.JLabel();
        IconHamb = new javax.swing.JLabel();
        Logo = new javax.swing.JPanel();
        ImgRest = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 341, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 426, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        PanelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setBackground(new java.awt.Color(255, 255, 0));
        Titulo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                TituloMouseDragged(evt);
            }
        });
        Titulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TituloMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                TituloMouseReleased(evt);
            }
        });

        PanelCerrar.setBackground(new java.awt.Color(255, 0, 0));
        PanelCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelCerrarMouseClicked(evt);
            }
        });
        PanelCerrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LetraX.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        LetraX.setForeground(new java.awt.Color(255, 255, 255));
        LetraX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LetraX.setText("X");
        LetraX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LetraXMouseClicked(evt);
            }
        });
        PanelCerrar.add(LetraX, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 30, 40));

        javax.swing.GroupLayout TituloLayout = new javax.swing.GroupLayout(Titulo);
        Titulo.setLayout(TituloLayout);
        TituloLayout.setHorizontalGroup(
            TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TituloLayout.createSequentialGroup()
                .addComponent(PanelCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 821, Short.MAX_VALUE))
        );
        TituloLayout.setVerticalGroup(
            TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        PanelFondo.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 70));

        Letras.setBackground(new java.awt.Color(255, 255, 255));

        Reservar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Reservar.setText("RESERVAR");
        Reservar.setBorder(new javax.swing.border.MatteBorder(null));
        Reservar.setEnabled(false);
        Reservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReservarActionPerformed(evt);
            }
        });

        Nombre.setText("Nombre del cliente:");

        Nom.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Nom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                NomKeyReleased(evt);
            }
        });

        Texto.setFont(new java.awt.Font("Bradley Hand ITC", 1, 24)); // NOI18N
        Texto.setForeground(new java.awt.Color(255, 51, 0));
        Texto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Texto.setText("TBB - THE BEST BURGER");

        IconHamb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imag/hamburguesa.png"))); // NOI18N

        javax.swing.GroupLayout LetrasLayout = new javax.swing.GroupLayout(Letras);
        Letras.setLayout(LetrasLayout);
        LetrasLayout.setHorizontalGroup(
            LetrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LetrasLayout.createSequentialGroup()
                .addGroup(LetrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LetrasLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Nom, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(LetrasLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(Texto, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(LetrasLayout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(IconHamb)))
                .addContainerGap(52, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LetrasLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Reservar, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        LetrasLayout.setVerticalGroup(
            LetrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LetrasLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(IconHamb)
                .addGap(58, 58, 58)
                .addComponent(Texto, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addGroup(LetrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nom, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(Reservar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );

        PanelFondo.add(Letras, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 570, 540));

        Logo.setBackground(new java.awt.Color(0, 255, 204));
        Logo.setForeground(new java.awt.Color(255, 255, 255));

        ImgRest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imag/restaurant.jpg"))); // NOI18N
        ImgRest.setText("jLabel3");

        javax.swing.GroupLayout LogoLayout = new javax.swing.GroupLayout(Logo);
        Logo.setLayout(LogoLayout);
        LogoLayout.setHorizontalGroup(
            LogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogoLayout.createSequentialGroup()
                .addComponent(ImgRest, javax.swing.GroupLayout.PREFERRED_SIZE, 314, Short.MAX_VALUE)
                .addContainerGap())
        );
        LogoLayout.setVerticalGroup(
            LogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ImgRest, javax.swing.GroupLayout.PREFERRED_SIZE, 530, Short.MAX_VALUE)
        );

        PanelFondo.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 70, 320, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 885, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LetraXMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LetraXMouseClicked
      //Lo hacemos en el label donde está la X para que se salga cuando pulsen en cualquier lado del cuadro rojo
        System.exit(0);
    }//GEN-LAST:event_LetraXMouseClicked

    private void PanelCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelCerrarMouseClicked
      //Para cerrar la app
       System.exit(0);
    }//GEN-LAST:event_PanelCerrarMouseClicked

    private void NomKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NomKeyReleased
      //getText(obtenemos el valor que tiene, si hay algo escrito) 
      //Si el campo Nom está vacío.  
        if(Nom.getText().isEmpty()){
        Reservar.setEnabled(false);
        }else
      Reservar.setEnabled(true);
    }//GEN-LAST:event_NomKeyReleased

    private void ReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReservarActionPerformed
 //Estio hace que cuando se clike el botón Reservar, se abra la ventana Reservas (La otra clase)  
        Reservas v = new Reservas();
         v.show();
  //Cuando se abra la clase Reservas, se cierra la Principal
  //Utilizamos hide porque lo que queremos es esconder la pantalla, si kisieramos cerrar la app utilizaríamos el (system.exit = 0;)
       this.hide();
    }//GEN-LAST:event_ReservarActionPerformed

    private void TituloMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TituloMousePressed
     //Le damos valor a las dos variables creadas arriba del todo para poder mover la app
     xMouse =evt.getX();
     yMouse = evt.getY();
     //Le cambiamos la forma al ratón para indicarle al cliente que el panel se puede mover
     Titulo.setCursor(Cursor.getPredefinedCursor(Cursor.MOVE_CURSOR));  
     //con el MouseDragged, creamos el método para que se mueva el panel (ABAJO)
    }//GEN-LAST:event_TituloMousePressed

    private void TituloMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TituloMouseDragged
        //Para que se mueva el panel
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_TituloMouseDragged

    private void TituloMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TituloMouseReleased
       //Para quitarle la forma al ratón que le hemos puesto antes para mover el panel, una vezx se deje de presionar el botón
       Titulo.setCursor(Cursor.getDefaultCursor());
    }//GEN-LAST:event_TituloMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IconHamb;
    private javax.swing.JLabel ImgRest;
    private javax.swing.JLabel LetraX;
    private javax.swing.JPanel Letras;
    private javax.swing.JPanel Logo;
    private javax.swing.JTextField Nom;
    private javax.swing.JLabel Nombre;
    private javax.swing.JPanel PanelCerrar;
    private javax.swing.JPanel PanelFondo;
    private javax.swing.JButton Reservar;
    private javax.swing.JLabel Texto;
    private javax.swing.JPanel Titulo;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
