/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package examendifeb;

import java.util.Locale;
import javafx.beans.value.ChangeListener;
import javafx.beans.value.ObservableValue;
import javax.swing.event.ChangeEvent;
import org.netbeans.validation.api.builtin.stringvalidation.StringValidators;
import org.netbeans.validation.api.ui.ValidationGroup;

/**
 *
 * @author rocio
 */
public class Reservas extends javax.swing.JFrame {

    /**
     * Creates new form Reservas
     */
    public Reservas() {
        initComponents();
    //Para crear la validación(letras en rojo)  
    ValidationGroup validador = validationPanel1.getValidationGroup();
    
    //Para validar que el campo nombre, no esté vacío
    validador.add(txt_nom_comp, StringValidators.REQUIRE_NON_EMPTY_STRING);
    //Para que el numero de telefono tenga 9 dígitos (para ello hacemos dos validaciones)
    //una para el máximo permitido y otra para el mínimo
    validador.add(Telef, StringValidators.minLength(9));
    validador.add(Telef, StringValidators.maxLength(9));
    //El numero de personas tiene que ser un entero
    validador.add(Num_pers, StringValidators.REQUIRE_VALID_INTEGER);
    //El numero de intolerantes, tiene que ser un entero
    validador.add(Num_intolerantes, StringValidators.REQUIRE_VALID_INTEGER);
    
    //Añadimos un lisener al panel validador(al panel de las letras rojas) para que cuando se valide y esté todo bien se habilite
    validationPanel1.addChangeListener( new javax.swing.event.ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent ce) {
             if(validationPanel1.getProblem()==null){
                Enviar.setEnabled(true);
                }else{
             //En caso contrario, permanece deshabilitado       
                Enviar.setEnabled(false);
                }
    
            }
    }    );

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
  //  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Franja_horaria = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        Panel_título = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_cerrar = new javax.swing.JButton();
        Panel_Lateral = new javax.swing.JPanel();
        Nom_completo = new javax.swing.JLabel();
        Telefono = new javax.swing.JLabel();
        Fech_reserva = new javax.swing.JLabel();
        Num_persona = new javax.swing.JLabel();
        Franja = new javax.swing.JLabel();
        Tipo_habit = new javax.swing.JLabel();
        Num_gluten = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Panel_Later_der = new javax.swing.JPanel();
        txt_nom_comp = new javax.swing.JTextField();
        Telef = new javax.swing.JTextField();
        Num_pers = new javax.swing.JTextField();
        Num_intolerantes = new javax.swing.JTextField();
        Rb_14 = new javax.swing.JRadioButton();
        Rb_19 = new javax.swing.JRadioButton();
        Rb_21 = new javax.swing.JRadioButton();
        Volver = new javax.swing.JButton();
        Enviar = new javax.swing.JButton();
        Tip_hamb = new javax.swing.JComboBox<>();
        validationPanel1 = new org.netbeans.validation.api.ui.swing.ValidationPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel_título.setBackground(new java.awt.Color(255, 255, 102));
        Panel_título.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("RESERVAS");
        Panel_título.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        btn_cerrar.setBackground(new java.awt.Color(255, 0, 0));
        btn_cerrar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_cerrar.setForeground(new java.awt.Color(255, 255, 255));
        btn_cerrar.setText("X");
        Panel_título.add(btn_cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 60, 50));

        jPanel1.add(Panel_título, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 450, 50));

        Panel_Lateral.setBackground(new java.awt.Color(255, 255, 204));

        Nom_completo.setText("Nombre completo:");

        Telefono.setText("Telefono:");

        Fech_reserva.setText("Fecha de reserva:");

        Num_persona.setText("Numero de personas:");

        Franja.setText("Franja horaria:");

        Tipo_habit.setText("Tipo de hamburguesas:");

        Num_gluten.setText("Nº intolerantes al gluten:");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imag/hamburguesa.png"))); // NOI18N

        javax.swing.GroupLayout Panel_LateralLayout = new javax.swing.GroupLayout(Panel_Lateral);
        Panel_Lateral.setLayout(Panel_LateralLayout);
        Panel_LateralLayout.setHorizontalGroup(
            Panel_LateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_LateralLayout.createSequentialGroup()
                .addGroup(Panel_LateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_LateralLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(Panel_LateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Telefono)
                            .addComponent(Fech_reserva)
                            .addComponent(Franja)
                            .addComponent(Tipo_habit)
                            .addComponent(Num_gluten)
                            .addComponent(Num_persona)
                            .addComponent(Nom_completo, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Panel_LateralLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel2)))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        Panel_LateralLayout.setVerticalGroup(
            Panel_LateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_LateralLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addGap(78, 78, 78)
                .addComponent(Nom_completo)
                .addGap(18, 18, 18)
                .addComponent(Telefono)
                .addGap(30, 30, 30)
                .addComponent(Fech_reserva, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Num_persona)
                .addGap(18, 18, 18)
                .addComponent(Franja)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Tipo_habit)
                .addGap(18, 18, 18)
                .addComponent(Num_gluten)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jPanel1.add(Panel_Lateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 480));

        Telef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelefActionPerformed(evt);
            }
        });

        Franja_horaria.add(Rb_14);
        Rb_14.setSelected(true);
        Rb_14.setText("De 14 a 16h");

        Franja_horaria.add(Rb_19);
        Rb_19.setText("De 19 a 21h");

        Franja_horaria.add(Rb_21);
        Rb_21.setText("De 21 a 23h");

        Volver.setText("Volver");

        Enviar.setText("Enviar");
        Enviar.setEnabled(false);

        Tip_hamb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sencilla", "Especiales", "Edición limitada" }));

        validationPanel1.setBackground(new java.awt.Color(0, 204, 204));

        javax.swing.GroupLayout Panel_Later_derLayout = new javax.swing.GroupLayout(Panel_Later_der);
        Panel_Later_der.setLayout(Panel_Later_derLayout);
        Panel_Later_derLayout.setHorizontalGroup(
            Panel_Later_derLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Later_derLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Volver)
                .addGap(108, 108, 108)
                .addComponent(Enviar)
                .addGap(31, 31, 31))
            .addGroup(Panel_Later_derLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(Panel_Later_derLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_Later_derLayout.createSequentialGroup()
                        .addComponent(Tip_hamb, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_Later_derLayout.createSequentialGroup()
                        .addGroup(Panel_Later_derLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(Panel_Later_derLayout.createSequentialGroup()
                                .addGap(0, 33, Short.MAX_VALUE)
                                .addComponent(validationPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_nom_comp, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Telef, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Panel_Later_derLayout.createSequentialGroup()
                                .addGroup(Panel_Later_derLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Num_pers, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Num_intolerantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(Panel_Later_derLayout.createSequentialGroup()
                                        .addComponent(Rb_14)
                                        .addGap(18, 18, 18)
                                        .addComponent(Rb_19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Rb_21)))
                                .addGap(0, 24, Short.MAX_VALUE)))
                        .addGap(52, 52, 52))))
        );
        Panel_Later_derLayout.setVerticalGroup(
            Panel_Later_derLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Later_derLayout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addComponent(validationPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_nom_comp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Telef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(Num_pers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_Later_derLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Rb_14)
                    .addComponent(Rb_19)
                    .addComponent(Rb_21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Tip_hamb, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Num_intolerantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(Panel_Later_derLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Enviar)
                    .addComponent(Volver))
                .addGap(14, 14, 14))
        );

        jPanel1.add(Panel_Later_der, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 450, 430));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TelefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelefActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelefActionPerformed

    private void txt_nom_compActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nom_compActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nom_compActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reservas().setVisible(true);
            //Para que cuando creemos nuestro archivo personalizado,los textos de la validación(el texto en rojo), sea en español   
                Locale.setDefault(new Locale("es", "ES"));
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Enviar;
    private javax.swing.JLabel Fech_reserva;
    private javax.swing.JLabel Franja;
    private javax.swing.ButtonGroup Franja_horaria;
    private javax.swing.JLabel Nom_completo;
    private javax.swing.JLabel Num_gluten;
    private javax.swing.JTextField Num_intolerantes;
    private javax.swing.JTextField Num_pers;
    private javax.swing.JLabel Num_persona;
    private javax.swing.JPanel Panel_Later_der;
    private javax.swing.JPanel Panel_Lateral;
    private javax.swing.JPanel Panel_título;
    private javax.swing.JRadioButton Rb_14;
    private javax.swing.JRadioButton Rb_19;
    private javax.swing.JRadioButton Rb_21;
    private javax.swing.JTextField Telef;
    private javax.swing.JLabel Telefono;
    private javax.swing.JComboBox<String> Tip_hamb;
    private javax.swing.JLabel Tipo_habit;
    private javax.swing.JButton Volver;
    private javax.swing.JButton btn_cerrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_nom_comp;
    private org.netbeans.validation.api.ui.swing.ValidationPanel validationPanel1;
    // End of variables declaration//GEN-END:variables
}
